/**
 * 运行日志展示——**标签/常量桶**（FE-COMPONENT-SPLIT-B2 拆分桶之一）。
 *
 * 由 `runtimeLogPresentation.ts`（506 行，超 500 硬红线）拆出：本桶只承载
 * 静态标签与顺序常量，**无逻辑、无依赖**，供 view/format 桶引用。
 * 拆分纪律：内容逐字搬移，行为不变；对外导出面由 `index.ts` barrel 统一保住。
 */

export const TARGET_LABELS: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /^http_access$/i, label: '网页请求' },
  { pattern: /^compat_access$/i, label: '兼容客户端请求' },
  { pattern: /^fmby_server$/i, label: '服务进程' },
  { pattern: /playback::service::context/i, label: '播放上下文' },
  { pattern: /playback::service::targets/i, label: '播放目标解析' },
  { pattern: /playback::service::prefetch/i, label: '播放预热' },
  { pattern: /metadata::worker/i, label: '技术参数探测工人' },
  { pattern: /manage::runtime_logs/i, label: '运行日志解析' },
  { pattern: /routes::playback_core/i, label: '兼容播放路由' },
];

export const EVENT_LABELS: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /^compat user item detail request$/i, label: '兼容详情请求' },
  { pattern: /^compat playback info request$/i, label: '兼容播放信息请求' },
  { pattern: /^compat resolve_playable_item_id$/i, label: '解析可播放媒体项' },
  { pattern: /^compat PlaybackInfo decision ok$/i, label: '兼容播放决策成功' },
  { pattern: /^compat PlaybackInfo decision failed$/i, label: '兼容播放决策失败' },
  { pattern: /^compat PlaybackInfo built stream url$/i, label: '已生成兼容播放地址' },
  { pattern: /^compat item stream request$/i, label: '兼容流请求' },
  { pattern: /^compat stream -> redirect$/i, label: '兼容流重定向到远端' },
  { pattern: /^playback build_context: item found$/i, label: '已找到媒体项' },
  { pattern: /^playback build_context: available source$/i, label: '发现可用来源' },
  { pattern: /^playback build_context: selected source$/i, label: '已选中来源' },
  { pattern: /^playback source select: no playable source available$/i, label: '没有可用播放源' },
  { pattern: /^playback resolve_provider_target start$/i, label: '开始解析播放目标' },
  { pattern: /^playback resolve_provider_target: remote cache hit$/i, label: '远端缓存命中' },
  { pattern: /^playback resolve_provider_target: remote cache miss$/i, label: '远端缓存未命中' },
  { pattern: /^playback resolve_provider_target: upstream resolved$/i, label: '远端解析完成' },
  { pattern: /^playback resolve_provider_target: redirect url$/i, label: '已获得跳转地址' },
  { pattern: /^playback remote redirect prewarm ok$/i, label: '远端跳转预热成功' },
  { pattern: /^playback detail prewarm finished$/i, label: '详情预热完成' },
  { pattern: /^请求完成$/i, label: '请求完成' },
  { pattern: /^请求失败$/i, label: '请求失败' },
];

export const FIELD_LABELS: Record<string, string> = {
  method: '请求方式',
  path: '请求路径',
  status: '状态码',
  elapsed_ms: '耗时',
  client: '客户端',
  ip: 'IP 地址',
  request_size: '请求体大小',
  content_type: '内容类型',
  request_id: '请求 ID',
  user_id: '用户 ID',
  username: '用户名',
  display_name: '显示名称',
  item_id: '媒体项 ID',
  effective_item_id: '生效媒体项 ID',
  source_id: '来源 ID',
  media_source_id: '媒体来源 ID',
  preferred_source_id: '首选来源 ID',
  session_id: '会话 ID',
  mount_id: '挂载点 ID',
  library_id: '媒体库 ID',
  task_id: '任务 ID',
  reason: '原因',
  error: '错误详情',
  source_status: '来源状态',
  provider_type: '来源类型',
  file_path: '文件路径',
  redirect_url: '跳转地址',
  final_url: '最终地址',
  query: '查询参数',
  token_carrier: '令牌来源',
  token_hash_prefix: '令牌指纹',
  media_type: '媒体类型',
  title: '标题',
  container: '封装格式',
  range: 'Range 请求头',
  base_url: '基础地址',
  compat_stream_url: '兼容流地址',
  stream_url: '流地址',
  direct_url: '直连地址',
  external_direct_url: '外部直连地址',
  direct_play_candidate: '可直连播放',
  resolve_reason: '解析原因',
  cached_until: '缓存有效期',
  resolved_at: '解析时间',
  expires_at: '过期时间',
  duration_ticks: '时长',
  sources_count: '来源数量',
  user_agent_hash: '客户端指纹',
};

/** 主字段展示顺序（在此序列内的字段进 primaryFields，其余进 extraFields）。 */
export const PRIMARY_FIELD_ORDER = [
  'status',
  'elapsed_ms',
  'method',
  'path',
  'client',
  'ip',
  'request_id',
  'username',
  'display_name',
  'user_id',
  'item_id',
  'effective_item_id',
  'source_id',
  'media_source_id',
  'preferred_source_id',
  'source_status',
  'provider_type',
  'file_path',
  'reason',
  'error',
  'request_size',
  'content_type',
];

export const HTTP_STATUS_LABELS: Record<number, string> = {
  200: '成功',
  201: '已创建',
  202: '已接收',
  204: '无返回内容',
  206: '部分内容',
  301: '永久跳转',
  302: '临时跳转',
  304: '未修改',
  400: '请求错误',
  401: '未授权',
  403: '禁止访问',
  404: '未找到',
  409: '冲突',
  410: '已删除',
  412: '前置条件失败',
  416: '范围无效',
  422: '请求无法处理',
  429: '请求过多',
  500: '服务内部错误',
  502: '网关错误',
  503: '服务不可用',
  504: '网关超时',
};
