import type { BatchDeleteManageUsersRequest, BatchDeleteRegistrationCodeBatchesRequest, BatchDisableManageUsersRequest, BatchUpdateManageUsersRequest, CreateManageUserRequest, BrowseManageMountDirectoriesRequest, CreateManageLibraryRequest, CreateManageMountRequest, CreateRegistrationCodeRequest, CreateRoleTemplateRequest, DangerousActionRequest, ManageActionResult, ManageAdvancedResponse, ManageAuditLogsResponse, ManageBatchUsersActionResponse, ManageBatchRegistrationCodeActionResponse, ManageLibrariesQuery, ManageLibrariesResponse, ManageLibraryDetailRecord, ManageMountDetailRecord, ManageMountDirectoryBrowserResponse, ManageMountsQuery, ManageMountsResponse, ManageOverviewResponse, ManageProbeTaskDetailRecord, ManageProbeTasksQuery, ManageProbeTasksResponse, ManageRegistrationCodesResponse, ManageRoleTemplatesResponse, ManageRuntimeLogsQuery, ManageRuntimeLogsResponse, ResetIpLoginRiskRequest, ResetUserLoginRiskRequest, ResetUserPasswordRequest, ReviewUserRegistrationRequest, ManageScanTriggerResult, ManageScansQuery, ManageScansResponse, ManageSourceAvailabilityRecoverResponse, ManageUserDetailRecord, ManageUsersQuery, ManageSessionsResponse, TriggerManageLibraryScanRequest, UpdateManageLibraryRequest, UpdateManageMountRequest, UpdateManageUserRequest, UpdateRegistrationCodeBatchRequest, ManageUsersResponse, UpdateRegistrationCodeRequest, UpdateRegistrationCodeStatusRequest, UpdateRoleTemplateRequest, UpdateUserStatusRequest } from "./types";
export declare const manageApi: {
    getOverview(): Promise<ManageOverviewResponse>;
    recoverUnavailableLibrarySource(librarySourceId: string): Promise<ManageSourceAvailabilityRecoverResponse>;
    getUsers(query?: ManageUsersQuery): Promise<ManageUsersResponse>;
    getUserDetail(userId: string): Promise<ManageUserDetailRecord>;
    createUser(payload: CreateManageUserRequest): Promise<ManageUserDetailRecord>;
    updateUser(userId: string, payload: UpdateManageUserRequest): Promise<ManageUserDetailRecord>;
    batchUpdateUsers(payload: BatchUpdateManageUsersRequest): Promise<ManageBatchUsersActionResponse>;
    batchDisableUsers(payload: BatchDisableManageUsersRequest): Promise<ManageBatchUsersActionResponse>;
    batchDeleteUsers(payload: BatchDeleteManageUsersRequest): Promise<ManageBatchUsersActionResponse>;
    updateUserStatus(userId: string, payload: UpdateUserStatusRequest): Promise<void>;
    approveUserRegistration(userId: string, payload: ReviewUserRegistrationRequest): Promise<ManageUserDetailRecord>;
    rejectUserRegistration(userId: string, payload: ReviewUserRegistrationRequest): Promise<ManageUserDetailRecord>;
    resetUserPassword(userId: string, payload: ResetUserPasswordRequest): Promise<ManageActionResult>;
    resetIpLoginRisk(payload: ResetIpLoginRiskRequest): Promise<ManageActionResult>;
    resetUserLoginRisk(userId: string, payload: ResetUserLoginRiskRequest): Promise<ManageActionResult>;
    getRegistrationCodes(): Promise<ManageRegistrationCodesResponse>;
    createRegistrationCode(payload: CreateRegistrationCodeRequest): Promise<{
        id: string;
        name: string;
        mode: "single-use-batch" | "shared-code";
        totalCodes: number;
        availableCodes: number;
        usedCodes: number;
        disabledCodes: number;
        expiredCodes: number;
        totalUsedCount: number;
        createdById: string;
        createdByName: string;
        createdAt: string;
        items: {
            id: string;
            batchId: string;
            code: string;
            roleTemplate: import("./types").ManageUserRole;
            roleTemplateLabel: string;
            status: "active" | "paused" | "expired" | "used-up";
            usageCount: number;
            usageLimit: number;
            maxSessions: number | undefined;
            validDays: number | undefined;
            expiresAt: string | undefined;
            defaultLibraries: string[];
            allowReactivation: boolean;
            requireApproval: boolean;
            createdById: string;
            createdByName: string;
            createdAt: string;
        }[];
    }>;
    updateRegistrationCode(codeId: string, payload: UpdateRegistrationCodeRequest): Promise<{
        id: string;
        batchId: string;
        code: string;
        roleTemplate: import("./types").ManageUserRole;
        roleTemplateLabel: string;
        status: "active" | "paused" | "expired" | "used-up";
        usageCount: number;
        usageLimit: number;
        maxSessions: number | undefined;
        validDays: number | undefined;
        expiresAt: string | undefined;
        defaultLibraries: string[];
        allowReactivation: boolean;
        requireApproval: boolean;
        createdById: string;
        createdByName: string;
        createdAt: string;
    }>;
    updateRegistrationCodeBatch(batchId: string, payload: UpdateRegistrationCodeBatchRequest): Promise<{
        id: string;
        name: string;
        mode: "single-use-batch" | "shared-code";
        totalCodes: number;
        availableCodes: number;
        usedCodes: number;
        disabledCodes: number;
        expiredCodes: number;
        totalUsedCount: number;
        createdById: string;
        createdByName: string;
        createdAt: string;
        items: {
            id: string;
            batchId: string;
            code: string;
            roleTemplate: import("./types").ManageUserRole;
            roleTemplateLabel: string;
            status: "active" | "paused" | "expired" | "used-up";
            usageCount: number;
            usageLimit: number;
            maxSessions: number | undefined;
            validDays: number | undefined;
            expiresAt: string | undefined;
            defaultLibraries: string[];
            allowReactivation: boolean;
            requireApproval: boolean;
            createdById: string;
            createdByName: string;
            createdAt: string;
        }[];
    }>;
    updateRegistrationCodeStatus(codeId: string, payload: UpdateRegistrationCodeStatusRequest): Promise<void>;
    deleteRegistrationCode(codeId: string, payload?: DangerousActionRequest): Promise<ManageActionResult>;
    batchDeleteRegistrationCodeBatches(payload: BatchDeleteRegistrationCodeBatchesRequest): Promise<ManageBatchRegistrationCodeActionResponse>;
    getRoleTemplates(): Promise<ManageRoleTemplatesResponse>;
    createRoleTemplate(payload: CreateRoleTemplateRequest): Promise<unknown>;
    updateRoleTemplate(templateId: string, payload: UpdateRoleTemplateRequest): Promise<unknown>;
    deleteRoleTemplate(templateId: string, payload?: DangerousActionRequest): Promise<ManageActionResult>;
    getSessions(): Promise<ManageSessionsResponse>;
    revokeSession(sessionId: string, payload?: DangerousActionRequest): Promise<void>;
    getAuditLogs(): Promise<ManageAuditLogsResponse>;
    getRuntimeLogs(query?: ManageRuntimeLogsQuery): Promise<ManageRuntimeLogsResponse>;
    getAdvanced(): Promise<ManageAdvancedResponse>;
    getLibraries(query?: ManageLibrariesQuery): Promise<ManageLibrariesResponse>;
    getLibraryDetail(libraryId: string): Promise<ManageLibraryDetailRecord>;
    createLibrary(payload: CreateManageLibraryRequest): Promise<ManageLibraryDetailRecord>;
    updateLibrary(libraryId: string, payload: UpdateManageLibraryRequest): Promise<ManageLibraryDetailRecord>;
    deleteLibrary(libraryId: string, payload?: DangerousActionRequest): Promise<ManageActionResult>;
    triggerLibraryScan(libraryId: string, payload?: TriggerManageLibraryScanRequest): Promise<ManageScanTriggerResult>;
    getMounts(query?: ManageMountsQuery): Promise<ManageMountsResponse>;
    getMountDetail(mountId: string): Promise<ManageMountDetailRecord>;
    createMount(payload: CreateManageMountRequest): Promise<ManageMountDetailRecord>;
    browseMountDirectories(payload: BrowseManageMountDirectoriesRequest): Promise<ManageMountDirectoryBrowserResponse>;
    updateMount(mountId: string, payload: UpdateManageMountRequest): Promise<ManageMountDetailRecord>;
    deleteMount(mountId: string, payload?: DangerousActionRequest): Promise<ManageActionResult>;
    validateMount(mountId: string): Promise<ManageMountDetailRecord>;
    refreshMountAccess(mountId: string): Promise<ManageMountDetailRecord>;
    getScans(query?: ManageScansQuery): Promise<ManageScansResponse>;
    getProbeTasks(query?: ManageProbeTasksQuery): Promise<ManageProbeTasksResponse>;
    getProbeTaskDetail(sourceId: string): Promise<ManageProbeTaskDetailRecord>;
    enqueueProbeTask(sourceId: string): Promise<ManageActionResult>;
    refreshProbeTask(sourceId: string): Promise<ManageActionResult>;
};
//# sourceMappingURL=api.d.ts.map