export { manageApi } from "./api";
export type {
  AdvancedMaintenanceAction,
  AuditLogRecord,
  BatchDeleteManageUsersRequest,
  BatchDeleteRegistrationCodeBatchesRequest,
  BatchDisableManageUsersRequest,
  BatchUpdateManageUsersRequest,
  CreateManageUserRequest,
  CreateManageLibraryRequest,
  CreateManageMountRequest,
  CreateRegistrationCodeRequest,
  CreateRoleTemplateRequest,
  DangerousActionRequest,
  ManageActivityItem,
  ManageActionResult,
  ManageAdvancedResponse,
  ManageAuditLogsResponse,
  ManageBatchUsersActionResponse,
  ManageBatchRegistrationCodeActionResponse,
  ManageKpi,
  ManageLibrariesResponse,
  ManageLibrariesQuery,
  ManageLibraryRecord,
  ManageLibraryDetailRecord,
  ManageLibraryGrantRecord,
  ManageLibrarySourceBindingInput,
  ManageLibrarySourceBindingRecord,
  ManageLibraryType,
  ManageMountLinkedLibrary,
  ManageMountLinkedSourceRecord,
  ManageMountRecord,
  ManageMountDetailRecord,
  ManageMountDirectoryEntry,
  ManageMountDirectoryBrowserResponse,
  ManageMountsResponse,
  ManageMountsQuery,
  ManageMountProviderType,
  ManageOverviewResponse,
  ManageProbeTaskDetailRecord,
  ManageProbeTaskRecord,
  ManageProbeTaskStatus,
  ManageProbeTaskStreamRecord,
  ManageProbeTasksQuery,
  ManageProbeTasksResponse,
  ManageProbeTechnicalSummary,
  ManageQuickLink,
  ResetIpLoginRiskRequest,
  ResetUserLoginRiskRequest,
  ResetUserPasswordRequest,
  ReviewUserRegistrationRequest,
  ManageSourceAvailabilityRecoverResponse,
  ManageSourcePathGrantInput,
  ManageSourcePathGrantRecord,
  ManageSourcePathPolicyInput,
  ManageSourcePathPolicyRecord,
  ManageRegistrationCodesResponse,
  RegistrationCodeBatchMode,
  RegistrationCodeBatchRecord,
  ManageRoleTemplatesResponse,
  ManageRuntimeLogsQuery,
  ManageRuntimeLogsResponse,
  ManageScanStatus,
  ManageLibraryScanTriggerTask,
  ManageScanTaskRecord,
  ManageScanTaskType,
  ManageLibraryScanTriggerResult,
  ManageScansQuery,
  ManageScansResponse,
  ManageStorageCapabilitiesState,
  ManageSessionsResponse,
  ManageTodoItem,
  ManageUnavailableSourceSummary,
  ManageUserDetailRecord,
  ManageUserAccountKind,
  ManageUsersQuery,
  ManageUserRole,
  ManageUserRecord,
  ManageUsersResponse,
  RegistrationCodeRecord,
  RoleTemplateRecord,
  RoleTemplateStatus,
  RuntimeLogLevel,
  RuntimeLogRecord,
  RegistrationCodeStatus,
  SessionRecord,
  TriggerManageLibraryScanRequest,
  UpdateManageLibraryRequest,
  UpdateManageMountRequest,
  UpdateRegistrationCodeBatchRequest,
  UpdateRegistrationCodeRequest,
  UpdateRoleTemplateRequest,
  UpdateManageUserRequest,
  BrowseManageMountDirectoriesRequest,
  UserStatus,
  ManageMountHealthRecord,
  ManageMountsHealthQuery,
  ManageMountsHealthResponse,
  MOUNT_FAULT_KIND_CREDENTIAL_EXPIRED,
  ManageMountCredentialStatus,
  TelegramPasswordResetReceipt,
} from "./types";
export { adminApiTokensApi, mapAdminApiToken } from "./adminApiTokens";
export type { AdminApiToken, AdminApiTokenCreateInput } from "./adminApiTokens";
// fmby-web#8：CAS 编排面（后端 #42-N5 = /api/admin/cas/*）。
export { casAdminApi, mapCasFanoutStatus, mapCasDriveStatus } from "./casAdmin";
export type {
  CasDriveConfig,
  CasDriveStatus,
  CasFanoutStatus,
  CasReconcileReport,
} from "./casAdmin";
export { migrationApi } from "./migration";
export type {
  MigrationEntry,
  MigrationInspectResponse,
  MigrationExportResponse,
} from "./migration";
