import type { ManageActionResult, ManageAdvancedResponse, ManageUserAccountKind, UpdateRegistrationCodeStatusRequest, UpdateUserStatusRequest } from "../types";
import type { RawAuditLogRecord, RawManageActionResult, RawManageAdvancedResponse, RawManagedSessionRecord, RawManagedSourcePathGrantRecord, RawManagedUserRecord, RawRegistrationCodeBatchRecord, RawRegistrationCodeRecord, RawRoleTemplateRecord, RawRuntimeLogRecord } from "../raw-types";
export declare function mapUserRecord(raw: RawManagedUserRecord): {
    id: string;
    username: string;
    displayName: string | undefined;
    email: string | undefined;
    accountKind: ManageUserAccountKind;
    roles: import("..").ManageUserRole[];
    roleLabel: string;
    status: "active" | "disabled" | "locked" | "pending";
    libraryScopes: never[];
    sourceGrants: {
        mountId: string;
        pathPrefix: string;
        grantedAt: string;
        grantedBy: string | undefined;
    }[];
    maxSessions: number | undefined;
    maxConcurrentPlaybacks: number | undefined;
    validUntil: string | undefined;
    mustChangePassword: boolean;
    lastLoginAt: string | undefined;
    lastDevice: string | undefined;
    createdAt: string;
    updatedAt: string;
    recentClientInfo: string | undefined;
};
export declare function mapRegistrationCode(raw: RawRegistrationCodeRecord): {
    id: string;
    batchId: string;
    code: string;
    roleTemplate: import("..").ManageUserRole;
    roleTemplateLabel: string;
    status: "active" | "paused" | "expired" | "used-up";
    usageCount: number;
    usageLimit: number;
    maxSessions: number | undefined;
    validDays: number | undefined;
    expiresAt: string | undefined;
    defaultLibraries: string[];
    allowReactivation: boolean;
    requireApproval: boolean;
    createdById: string;
    createdByName: string;
    createdAt: string;
};
export declare function mapRegistrationCodeBatch(raw: RawRegistrationCodeBatchRecord): {
    id: string;
    name: string;
    mode: "single-use-batch" | "shared-code";
    totalCodes: number;
    availableCodes: number;
    usedCodes: number;
    disabledCodes: number;
    expiredCodes: number;
    totalUsedCount: number;
    createdById: string;
    createdByName: string;
    createdAt: string;
    items: {
        id: string;
        batchId: string;
        code: string;
        roleTemplate: import("..").ManageUserRole;
        roleTemplateLabel: string;
        status: "active" | "paused" | "expired" | "used-up";
        usageCount: number;
        usageLimit: number;
        maxSessions: number | undefined;
        validDays: number | undefined;
        expiresAt: string | undefined;
        defaultLibraries: string[];
        allowReactivation: boolean;
        requireApproval: boolean;
        createdById: string;
        createdByName: string;
        createdAt: string;
    }[];
};
export declare function mapRoleTemplateRecord(raw: RawRoleTemplateRecord): {
    id: string;
    code: string;
    name: string;
    description: string | undefined;
    capabilities: string[];
    defaultLibraries: string[];
    sourceGrants: {
        mountId: string;
        pathPrefix: string;
        grantedAt: string;
        grantedBy: string | undefined;
    }[];
    defaultMaxSessions: number | undefined;
    defaultMaxConcurrentPlaybacks: number | undefined;
    defaultValidDays: number | undefined;
    isSystem: boolean;
    status: "active" | "disabled";
    createdAt: string;
    updatedAt: string;
};
export declare function mapSessionRecord(raw: RawManagedSessionRecord): {
    id: string;
    userName: string;
    deviceName: string;
    clientName: string;
    clientHeader: string | undefined;
    ipAddress: string | undefined;
    status: "active" | "idle" | "expired" | "revoked";
    current: boolean;
    createdAt: string;
    lastActiveAt: string;
    nowPlaying: {
        mediaId: string;
        mediaTitle: string;
        episodeTitle: string | undefined;
        posterUrl: string | undefined;
        progressPercent: number | undefined;
        playMethod: "DirectPlay" | "DirectStream";
        bitrateKbps: number | undefined;
    } | undefined;
};
export declare function mapAuditLogRecord(raw: RawAuditLogRecord): {
    id: string;
    actorName: string;
    actionLabel: string;
    targetLabel: string;
    summary: string;
    result: "success" | "warning" | "failure";
    createdAt: string;
    traceId: string | undefined;
};
export declare function mapRuntimeLogRecord(raw: RawRuntimeLogRecord): {
    id: string;
    timestamp: string;
    level: "error" | "info" | "trace" | "debug" | "warn" | "unknown";
    target: string | undefined;
    message: string;
    requestId: string | undefined;
    sourceFile: string;
    rawLine: string;
};
export declare function mapAdvanced(raw: RawManageAdvancedResponse): ManageAdvancedResponse;
export declare function mapManageActionResult(raw: RawManageActionResult): ManageActionResult;
export declare function mapRoleLabelToApi(raw: string): "user" | "restricted_user" | "admin" | "super_admin";
export declare function mapUserStatusToApi(raw: UpdateUserStatusRequest["status"]): "active" | "disabled" | "pending_activation" | "suspended";
export declare function mapRegistrationCodeStatusToApi(raw: UpdateRegistrationCodeStatusRequest["status"]): "disabled" | "expired" | "available";
export declare function mapSourcePathGrantRecord(raw: RawManagedSourcePathGrantRecord): {
    mountId: string;
    pathPrefix: string;
    grantedAt: string;
    grantedBy: string | undefined;
};
//# sourceMappingURL=records.d.ts.map